<?php
    $fileName = basename((string)($procurement->document_url ?? ''));
    $extension = strtolower(pathinfo($fileName, PATHINFO_EXTENSION));
    $documentUrl = $fileName ? URLROOT . '/assets/uploads/procurements/' . rawurlencode($fileName) : null;
    $isPdf = $extension === 'pdf';
?>
<div class="procurement-page-wrapper">
    <section class="procurement-hero-section py-4 position-relative overflow-hidden"><div class="container position-relative" style="z-index:2"><nav aria-label="breadcrumb"><ol class="breadcrumb mb-3"><li class="breadcrumb-item"><a href="<?= URLROOT ?>/procurement" class="text-white-50 text-decoration-none">ประกาศจัดซื้อจัดจ้าง</a></li><li class="breadcrumb-item active text-white" aria-current="page">รายละเอียดประกาศ</li></ol></nav><span class="badge bg-white bg-opacity-15 text-white border border-white border-opacity-25 rounded-pill px-3 py-2 mb-3"><?= htmlspecialchars($procurement->category) ?></span><h1 class="h2 fw-bold text-white mb-2"><?= htmlspecialchars($procurement->title) ?></h1><p class="text-white-50 mb-0"><i class="bi bi-calendar3 me-1"></i>เผยแพร่ <?= date('d/m/Y', strtotime($procurement->published_at)) ?><?php if (!empty($procurement->budget_year)): ?> <span class="mx-2">|</span> ปีงบประมาณ <?= $procurement->budget_year ?><?php endif; ?></p></div></section>
    <main class="container py-5"><div class="row g-4"><div class="col-lg-8"><section class="card border-0 shadow-sm rounded-4 overflow-hidden"><div class="card-body p-4 p-md-5"><h2 class="h5 fw-bold mb-4">เอกสารประกอบประกาศ</h2><?php if ($documentUrl && $isPdf): ?><div class="ratio ratio-4x3 border rounded-3 overflow-hidden"><iframe src="<?= $documentUrl ?>#view=FitH" title="เอกสาร <?= htmlspecialchars($procurement->title) ?>"></iframe></div><?php elseif ($documentUrl): ?><div class="text-center py-5 bg-light rounded-3"><i class="bi bi-file-earmark-arrow-down display-5 text-primary d-block mb-3"></i><h3 class="h5">เอกสารพร้อมดาวน์โหลด</h3><p class="text-muted">ไฟล์ประเภท <?= strtoupper(htmlspecialchars($extension)) ?> ไม่รองรับการแสดงตัวอย่างในเบราว์เซอร์</p><a href="<?= $documentUrl ?>" class="btn btn-primary rounded-pill px-4" download><i class="bi bi-download me-1"></i>ดาวน์โหลดเอกสาร</a></div><?php else: ?><div class="text-center py-5 bg-light rounded-3"><i class="bi bi-file-earmark-x display-5 text-muted d-block mb-3"></i><p class="text-muted mb-0">ประกาศนี้ยังไม่มีเอกสารแนบ</p></div><?php endif; ?></div></section></div><aside class="col-lg-4"><div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4"><h2 class="h6 fw-bold mb-3">ข้อมูลประกาศ</h2><dl class="mb-0 small"><dt class="text-muted fw-normal mb-1">หมวดหมู่</dt><dd class="fw-semibold mb-3"><?= htmlspecialchars($procurement->category) ?></dd><dt class="text-muted fw-normal mb-1">วิธีจัดหา</dt><dd class="fw-semibold mb-3"><?= htmlspecialchars($procurement->method ?: '-') ?></dd><dt class="text-muted fw-normal mb-1">วงเงินงบประมาณ</dt><dd class="fw-semibold mb-3"><?= $procurement->project_budget ? '฿' . number_format($procurement->project_budget, 2) : '-' ?></dd><dt class="text-muted fw-normal mb-1">วันที่เผยแพร่</dt><dd class="fw-semibold mb-0"><?= date('d/m/Y', strtotime($procurement->published_at)) ?></dd></dl><?php if ($documentUrl): ?><hr><a href="<?= $documentUrl ?>" class="btn btn-outline-primary w-100 rounded-pill" download><i class="bi bi-download me-1"></i>ดาวน์โหลดไฟล์</a><?php endif; ?></div></div><a href="<?= URLROOT ?>/procurement" class="btn btn-link text-decoration-none mt-3"><i class="bi bi-arrow-left me-1"></i>กลับหน้าประกาศทั้งหมด</a></aside></div></main>
</div>
