ALTER TABLE appointments
    ADD COLUMN IF NOT EXISTS booking_ref VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS time_slot ENUM('morning', 'afternoon') NOT NULL DEFAULT 'morning',
    ADD COLUMN IF NOT EXISTS queue_code VARCHAR(20) NULL;

ALTER TABLE queues
    ADD COLUMN IF NOT EXISTS counter_number VARCHAR(50) NOT NULL DEFAULT '1',
    ADD COLUMN IF NOT EXISTS service_type VARCHAR(50) NOT NULL DEFAULT 'general',
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS estimated_wait_minutes INT NOT NULL DEFAULT 10,
    ADD COLUMN IF NOT EXISTS called_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMP NULL;
