<?php $isEdit = $project !== null; ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="fw-bold text-dark mb-1"><?= $page_title ?></h3><p class="text-muted small mb-0">ข้อมูลที่เผยแพร่จะปรากฏในหน้า CSR สาธารณะ</p></div><a href="<?= URLROOT ?>/admin/csr" class="btn btn-outline-secondary rounded-pill px-4">กลับ</a></div>
<div class="card-modern p-4 p-md-5"><form action="<?= URLROOT ?>/admin/csr/<?= $isEdit ? 'update/' . $project->id : 'create' ?>" method="POST" enctype="multipart/form-data"><?= \App\Helpers\Security::csrfField() ?><div class="row g-4">
<div class="col-md-6"><label class="form-label fw-bold">ชื่อบริษัท / องค์กร <span class="text-danger">*</span></label><input class="form-control form-control-modern" name="company_name" value="<?= htmlspecialchars($project->company_name ?? '') ?>" required></div>
<div class="col-md-6"><label class="form-label fw-bold">ชื่อโครงการ <span class="text-danger">*</span></label><input class="form-control form-control-modern" name="project_title" value="<?= htmlspecialchars($project->project_title ?? '') ?>" required></div>
<div class="col-12"><label class="form-label fw-bold">รายละเอียดความร่วมมือ <span class="text-danger">*</span></label><textarea class="form-control form-control-modern" name="summary" rows="4" required><?= htmlspecialchars($project->summary ?? '') ?></textarea></div>
<div class="col-md-6"><label class="form-label fw-bold">ผลลัพธ์หรือสิ่งที่สนับสนุน</label><input class="form-control form-control-modern" name="contribution" value="<?= htmlspecialchars($project->contribution ?? '') ?>" placeholder="เช่น สนับสนุนอุปกรณ์การแพทย์แก่ห้องฉุกเฉิน"></div>
<div class="col-md-3"><label class="form-label fw-bold">วันที่ดำเนินงาน</label><input type="date" class="form-control form-control-modern" name="project_date" value="<?= htmlspecialchars($project->project_date ?? '') ?>"></div>
<div class="col-md-3"><label class="form-label fw-bold">ลำดับแสดงผล</label><input type="number" min="0" class="form-control form-control-modern" name="sort_order" value="<?= (int)($project->sort_order ?? 0) ?>"></div>
<div class="col-md-6"><label class="form-label fw-bold">เว็บไซต์องค์กร</label><input type="url" class="form-control form-control-modern" name="website" value="<?= htmlspecialchars($project->website ?? '') ?>" placeholder="https://example.com"></div>
<div class="col-md-6"><label class="form-label fw-bold">รูปภาพโครงการ</label><input type="file" class="form-control form-control-modern" name="image" accept="image/jpeg,image/png,image/webp"><small class="text-muted">JPG, PNG หรือ WebP ขนาดไม่เกิน 3 MB</small></div>
<div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_published" id="is_published" <?= (!$isEdit || $project->is_published) ? 'checked' : '' ?>><label class="form-check-label fw-bold" for="is_published">เผยแพร่บนหน้า CSR</label></div></div>
</div><div class="text-end mt-5 pt-3 border-top"><a href="<?= URLROOT ?>/admin/csr" class="btn btn-light rounded-pill px-4 me-2">ยกเลิก</a><button class="btn btn-admin-primary rounded-pill px-5"><i class="bi bi-save me-1"></i>บันทึก</button></div></form></div>
