<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4">
    <div><h3 class="fw-bold text-dark mb-1"><?= $page_title ?></h3><p class="text-muted small mb-0">เผยแพร่ความร่วมมือกับบริษัทและภาคีเครือข่ายบนหน้า CSR</p></div>
    <a href="<?= URLROOT ?>/admin/csr/create" class="btn btn-admin-primary rounded-pill px-4"><i class="bi bi-plus-lg me-1"></i>เพิ่มโครงการ CSR</a>
</div>
<?php if ($msg = \App\Core\Controller::getFlash('csr_success')): ?><div class="alert alert-success border-0 rounded-4"><?= htmlspecialchars($msg['message'] ?? $msg) ?></div><?php endif; ?>
<?php if ($msg = \App\Core\Controller::getFlash('csr_error')): ?><div class="alert alert-warning border-0 rounded-4"><?= htmlspecialchars($msg['message'] ?? $msg) ?></div><?php endif; ?>
<div class="card-modern overflow-hidden"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">บริษัท / โครงการ</th><th>วันที่</th><th>สถานะ</th><th class="text-end pe-4">จัดการ</th></tr></thead><tbody>
<?php if (empty($projects)): ?><tr><td colspan="4" class="text-center text-muted py-5"><i class="bi bi-building-heart fs-2 d-block mb-2"></i>ยังไม่มีโครงการ CSR</td></tr><?php endif; ?>
<?php foreach ($projects as $project): ?><tr><td class="ps-4"><div class="fw-bold"><?= htmlspecialchars($project->company_name) ?></div><small class="text-muted"><?= htmlspecialchars($project->project_title) ?></small></td><td><?= $project->project_date ? date('d/m/Y', strtotime($project->project_date)) : '-' ?></td><td><span class="badge <?= $project->is_published ? 'bg-success-subtle text-success' : 'bg-secondary-subtle text-secondary' ?> rounded-pill px-3"><?= $project->is_published ? 'เผยแพร่' : 'ฉบับร่าง' ?></span></td><td class="text-end pe-4"><a href="<?= URLROOT ?>/admin/csr/edit/<?= $project->id ?>" class="btn btn-sm btn-outline-primary rounded-3"><i class="bi bi-pencil"></i></a><form action="<?= URLROOT ?>/admin/csr/delete/<?= $project->id ?>" method="POST" class="d-inline" onsubmit="return confirm('ยืนยันการลบโครงการ CSR นี้?');"><?= \App\Helpers\Security::csrfField() ?><button class="btn btn-sm btn-outline-danger rounded-3"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; ?>
</tbody></table></div></div>
